### ISSUE TITLE
Morning Session Suggesstions

### ISSUE THREAD

**Issue by topeogunleye** [topeogunleye/todo-list#15]
### Morning Session Suggestions
- [x] Kindly add jsDom  properly to able able to test for DOM Manipulation in your test file :+1:

**Comment by edwardoluyara** [comment]
I think the project hasn't been completed but your are making progress 'Great job man! 👏'

**Comment by topeogunleye** [comment]
Hey @oluyaratosin123 , thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.
