### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by KingsleyIbe** [topeogunleye/todo-list#18]
Hi @topeogunleye, 💯 

![image](https://user-images.githubusercontent.com/43799727/160290858-72587f71-4f04-4085-a1b7-e747da92b763.png)

Great work on implementing the project. It looks great however, there are a few issues I want to draw your attention to:

- [x] Consider placing the count value just after the h1, it looks better that way.

Other than that, your project looks complete. Kudos!

Happy Coding Mate 😄

**Comment by topeogunleye** [comment]
Hey @KingsleyIbe, thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.
